apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      name: app-server
      labels:
        app: app-server
    spec:
      containers:
        - name: stori-file-processor-service
          image: asce616/stori:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "100Mi"  # Request 1GB of memory
            limits:
              memory: "380Mi"  # Limit memory usage to 2GB
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-server-service
  labels:
    app: app-server
spec:
  type: LoadBalancer
  selector:
    app: app-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
